# Generated by Django 3.2.6 on 2021-08-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام کنسرت')),
                ('Singer_Name', models.CharField(max_length=100, verbose_name='نام خواننده')),
                ('length', models.IntegerField(verbose_name='نام کنسرت')),
                ('Poster', models.ImageField(null=True, upload_to='concertImages/', verbose_name='پوستر')),
            ],
            options={
                'verbose_name': 'کنسرت',
                'verbose_name_plural': 'کنسرت',
            },
        ),
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام محل')),
                ('Address', models.CharField(default='تهران-برج میلاد', max_length=500, verbose_name='محل برگزاری')),
                ('Phone', models.CharField(max_length=11, null=True, verbose_name='شماره تماس')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
            ],
            options={
                'verbose_name': 'محل برگزاری',
                'verbose_name_plural': 'محل برگزاری',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('Gender', models.IntegerField(choices=[('man', 'مرد'), ('woman', 'زن')], verbose_name='جنسیت')),
                ('ProfileImage', models.ImageField(upload_to='ProfileImages/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.CreateModel(
            name='timeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField(verbose_name='تاریخ برگزاری')),
                ('Seats', models.IntegerField(verbose_name='تعداد صندلی')),
                ('Status', models.IntegerField(choices=[('Start', 'فروش بلیط شروع شده است'), ('End', 'فروش بلیط تمام شده است'), ('Cancel', 'این سانس کنسل شده است'), ('Sales', 'در حال فروش بلیط')], verbose_name='وضعیت کنسرت')),
                ('concertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.concertmodel', verbose_name='کنسرت')),
                ('locationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.locationmodel', verbose_name='محل برگزاری')),
            ],
            options={
                'verbose_name': 'سانس برگزاری',
                'verbose_name_plural': 'سانس برگزاری',
            },
        ),
        migrations.CreateModel(
            name='ticketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('Price', models.IntegerField(verbose_name='مبلغ')),
                ('TicketImage', models.ImageField(upload_to='TicketImages/', verbose_name='عکس')),
                ('ProfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.profilemodel', verbose_name='کاربر')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.timemodel', verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط',
            },
        ),
    ]
