# Generated by Django 3.2.6 on 2021-08-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Define the Concert model
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Concert Name')),
                ('singer_name', models.CharField(max_length=100, verbose_name='Singer Name')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('poster', models.ImageField(null=True, upload_to='concert_images/', verbose_name='Poster')),
            ],
            options={
                'verbose_name': 'Concert',
                'verbose_name_plural': 'Concerts',
            },
        ),
        # Define the Location model
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('address', models.CharField(default='Tehran-Milad Tower', max_length=500, verbose_name='Address')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Phone Number')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        # Define the Profile model
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='First Name')),
                ('family', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.IntegerField(choices=[('man', 'Male'), ('woman', 'Female')], verbose_name='Gender')),
                ('profile_image', models.ImageField(upload_to='profile_images/', verbose_name='Profile Image')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        # Define the Time model
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(verbose_name='Start Date and Time')),
                ('seats', models.IntegerField(verbose_name='Number of Seats')),
                ('status', models.IntegerField(choices=[('Start', 'Ticket Sales Started'), ('End', 'Ticket Sales Ended'), ('Cancel', 'Canceled'), ('Sales', 'Selling')], verbose_name='Status')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.Concert', verbose_name='Concert')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.Location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        # Define the Ticket model
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('ticket_image', models.ImageField(upload_to='ticket_images/', verbose_name='Ticket Image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.Profile', verbose_name='Profile')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.Time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
