# Generated by Django 3.2.6 on 2021-08-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertmodel',
            name='length',
            field=models.IntegerField(verbose_name='مدت زمان کنسرت'),
        ),
    ]
