# Generated by Django 3.2.6 on 2021-08-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0002_alter_concertmodel_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[(1, 'فروش بلیط شروع شده است'), (2, 'فروش بلیط تمام شده است'), (3, 'این سانس کنسل شده است'), (4, 'در حال فروش بلیط')], verbose_name='وضعیت کنسرت'),
        ),
    ]
